# Generated by Django 4.1.7 on 2023-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocradsam', '0003_student_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
